/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package at.idi.ichhassenetbeans;

/**
 *
 * @author stefiii
 */
public class Temperaturvieh extends javax.swing.JFrame {

    /**
     * Creates new form Temperaturvieh
     */
    public Temperaturvieh() {
        initComponents();
    }
    String eingbae = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input = new javax.swing.JTextField();
        output = new javax.swing.JLabel();
        CelsiusZuKelvin = new javax.swing.JButton();
        KelvinZuCelsius = new javax.swing.JButton();
        AusgabeZurEingabe = new javax.swing.JButton();
        CelsiusZuFahrenheit = new javax.swing.JButton();
        FahrenheitZuCelsius = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        CelsiusZuKelvin.setText("Clesius -> Kelvin");
        CelsiusZuKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelsiusZuKelvinActionPerformed(evt);
            }
        });

        KelvinZuCelsius.setText("Kelvin -> Celsius");
        KelvinZuCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelvinZuCelsiusActionPerformed(evt);
            }
        });

        AusgabeZurEingabe.setText("Ausgabe zu eingabe Konvertieren");
        AusgabeZurEingabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AusgabeZurEingabeActionPerformed(evt);
            }
        });

        CelsiusZuFahrenheit.setText("Celsius zu Fahrenheit");
        CelsiusZuFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelsiusZuFahrenheitActionPerformed(evt);
            }
        });

        FahrenheitZuCelsius.setText("Fahrenheit zu Celsius");
        FahrenheitZuCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FahrenheitZuCelsiusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(output)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CelsiusZuFahrenheit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FahrenheitZuCelsius))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CelsiusZuKelvin)
                        .addGap(18, 18, 18)
                        .addComponent(KelvinZuCelsius)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AusgabeZurEingabe))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelsiusZuKelvin)
                    .addComponent(KelvinZuCelsius)
                    .addComponent(AusgabeZurEingabe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelsiusZuFahrenheit)
                    .addComponent(FahrenheitZuCelsius))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CelsiusZuKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelsiusZuKelvinActionPerformed
        eingbae = input.getText();
        double tmp = Double.valueOf(eingbae);
        tmp = tmp + 273.15;
        String ergebnis = Double.toString(tmp);
        output.setText(ergebnis);
    }//GEN-LAST:event_CelsiusZuKelvinActionPerformed

    private void KelvinZuCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelvinZuCelsiusActionPerformed
        eingbae = input.getText();
        double tmp = Double.valueOf(eingbae);
        tmp = tmp - 273.15;
        String ergebnis = Double.toString(tmp);
        output.setText(ergebnis);
    }//GEN-LAST:event_KelvinZuCelsiusActionPerformed

    private void AusgabeZurEingabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AusgabeZurEingabeActionPerformed
        String output_text = output.getText();
        String input_text = input.getText();
        input.setText(output_text);
        output.setText(input_text);
        
    }//GEN-LAST:event_AusgabeZurEingabeActionPerformed

    private void CelsiusZuFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelsiusZuFahrenheitActionPerformed
        eingbae = input.getText();
        double tmp = Double.valueOf(eingbae);
        tmp = tmp * 1.8 + 32;
        String ergebnis = Double.toString(tmp);
        output.setText(ergebnis);
    }//GEN-LAST:event_CelsiusZuFahrenheitActionPerformed

    private void FahrenheitZuCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FahrenheitZuCelsiusActionPerformed
        eingbae = input.getText();
        double tmp = Double.valueOf(eingbae);
        tmp = (tmp-32)/1.8;
        String ergebnis = Double.toString(tmp);
        output.setText(ergebnis);
    }//GEN-LAST:event_FahrenheitZuCelsiusActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temperaturvieh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temperaturvieh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temperaturvieh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temperaturvieh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temperaturvieh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AusgabeZurEingabe;
    private javax.swing.JButton CelsiusZuFahrenheit;
    private javax.swing.JButton CelsiusZuKelvin;
    private javax.swing.JButton FahrenheitZuCelsius;
    private javax.swing.JButton KelvinZuCelsius;
    private javax.swing.JTextField input;
    private javax.swing.JLabel output;
    // End of variables declaration//GEN-END:variables
}
