services:
  db:
    image: mariadb:latest
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: something
    volumes:
      # - db_data:/var/lib/mysql
      - ./src/sql/script.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3306:3306"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./src/php:/var/www/public
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    restart: no

  webserver:
    image: nginx:latest
    container_name: name
    restart: no
    volumes:
      - ./src/php:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
# volumes:
#   db_data:
